### ISSUE TITLE
Przycisk "Edycja"

### ISSUE THREAD

**Issue by zibik** [dotevo/OSMZmiany#1]
W interfejsie powinien znaleźć się przycisk dający możliwość otworzenia wybranego obszaru (aktualnie widocznego) w swoim ulubionym edytorze JOSM.

**Comment by dotevo** [comment]
W potlatch2 juz jest (w JOSM na razie nie wiem jak zrobic, muszę dopiero poszukac)

**Comment by dotevo** [comment]
Podobno działa :P
