### ISSUE TITLE
add download location

### ISSUE THREAD

**Issue by matkoniecz** [dotevo/OSMZmiany#20]
Maybe I missed it but I see no download link - I checked https://github.com/Dotevo/OSMZmiany and http://wiki.openstreetmap.org/wiki/OSMZmiany

Option to download .jar would allow far more people to use this tool and make it easier for everybody.

**Comment by dotevo** [comment]
Is still here https://github.com/dotevo/OSMZmiany/downloads
and also here https://copy.com/cyZ8PcnvGj0A
