### ISSUE TITLE
Wyłapywanie "nowych"

### ISSUE THREAD

**Issue by zibik** [dotevo/OSMZmiany#3]
Nie wiem na ile to realne, ale może dałoby się coś takiego zrobić, aby program wyróżniał edycje popełnione przez świeżo zarejestrowanych użytkowników... chociaż jeśli będzie funkcja "białej listy" to i tak ich będzie można wyłapać :)

**Comment by dotevo** [comment]
Zrobiłem białą listę oraz czarną :) Inaczej wyłapywać mogę tylko po wysokości numeru ID. Na razie zamykam.
