### ISSUE TITLE
dodanie usera do listy

### ISSUE THREAD

**Issue by marimil** [dotevo/OSMZmiany#5]
Po dodaniu usera do listy, przy wlaczonej bialej, jego zmiany powiny zniknac. Teraz trzeba zmienic dwa razy liste, zeby zadzialalo albo czekac na dociagniecie kolejnych zmian.
Przy czarnej nie ma co dodawac, bo juz jest ale mimo to dodaje.

**Comment by dotevo** [comment]
Ok, poprawione.
