### ISSUE TITLE
remove box

### ISSUE THREAD

**Issue by marimil** [dotevo/OSMZmiany#6]
1. Wcisniecie przycisku nie likwiduje ramki. Chyba, ze dla uzytkownika, ktory sie rozmyslil i jeszcze raz chce ustawic ten prostokat.
2. Moze tak ma byc, ale po wcisnieciu tego przycisku, punkty lezace poza prostokatem ustawionym przyciskiem Set Box, juz nie wracaja na mape.

**Comment by dotevo** [comment]
1. Poprawione
2. Tak musi być, ze względu na pamięć komputera.
